# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# uv_nc_to_s_tif.py
# Created on: 2014-10-03 11:14:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
uwnd_sig995_2013_nc = "H:\\esm296-4f\\lab1\\raw\\uwnd.sig995.2013.nc"
vwnd_sig995_2013_nc = "H:\\esm296-4f\\lab1\\raw\\vwnd.sig995.2013.nc"
u__j_ = "u_%j%"
s_001 = "in_memory\\s_001"
v__j_ = "v_%j%"

# Process: For
arcpy.IterateCount_mb("1", "365", "29")

# Process: Make NetCDF Raster Layer
arcpy.MakeNetCDFRasterLayer_md(uwnd_sig995_2013_nc, "uwnd", "lon", "lat", u__j_, "", "time %j%", "BY_INDEX")

# Process: Make NetCDF Raster Layer (2)
arcpy.MakeNetCDFRasterLayer_md(vwnd_sig995_2013_nc, "vwnd", "lon", "lat", v__j_, "", "time %j%", "BY_INDEX")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("SquareRoot( Square(\"u_%j%\") + Square(\"v_%j%\") )", s_001)

